#if defined(ESP8266) || defined(ESP32)
#include <pgmspace.h>
#else
#include <avr/pgmspace.h>
#endif

// I did not find a way to get the length of the array
#define WISDOM_NUMBER_OF_TEXTS          (211)

// Latin-1 character codes
// ä: "\xe4"
// ü: "\xfc"
// ö: "\xf6"
// Ä: "\xc4"
// Ö: "\xd6"
// Ü: "\xdc"
// ß: "\xdf"

const String wisdomTexts [] PROGMEM = {
    // Bullshit Bingo
    "Bingo 1: It works on my Machine!",
    "Bingo 2: It worked yesterday!",
    "Bingo 3: I've never done that before.",
    "Bingo 4: That's weird.",
    "Bingo 5: Where were you when the program blew up?",
    "Bingo 6: Why do you want to do it that way?",
    "Bingo 7: You can't use that version on your System!",
    "Bingo 8: Even though it doesn't work how does it feel?",
    "Bingo 9: Did you check for a Virus on your System?",
    "Bingo 10: Somebody must have changed my code!",
    "Bingo 11: It works, but it hasn't been tested.",
    "Bingo 12: THIS can't be the source of that!",
    "Bingo 13: I can't test everything.",
    "Bingo 14: It's just some unlucky coincidence.",
    "Bingo 15: You must have the wrong version!",
    "Bingo 16: I haven't touched that module in weeks.",
    "Bingo 17: There is something funky in your data.",
    "Bingo 18: What did you Type in to get it to crash?",
    "Bingo 19: It must be a hardware problem.",
    "Bingo 20: How is that possible?",
    "Bingo 21: That's scheduled to be fixed in the next release.",
    "Bingo 22: Yes, we knew that would happen.",
    "Bingo 23: Maybe we just don't support that platform.",
    "Bingo 24: It's a Feature we just haven't updated the specs.",
    "Bingo 25: Surely Nobody is going to use the program like that.",
    // Julia
    "So m""\xfc""de wie heute, war ich bestimmt seit gestern nicht mehr.",
    "Geschenke einpacken. Das r""\xfc""ckw""\xe4""rts einparken der Frauen f""\xfc""r M""\xe4""nner.",
    "Je gr""\xf6""ßer der Dachschaden desto besser der Blick auf die Sterne.",
    "Ich kann doch nicht alle gl""\xfc""cklich machen oder sehe ich aus wie ein Glas Nutella?!",
    "Lass uns lachen, das Leben ist ernst genug.",
    "Ich f""\xfc""hle mich, als k""\xf6""nnte ich B""\xe4""ume ausreissen. Also, kleine B""\xe4""ume. Vielleicht Bambus. Oder Blumen. Na gut. Gras. Gras geht.",
    "Nat""\xfc""rlich mache ich gerne Sport. Deshalb auch so selten. Soll ja schließlich was Besonderes bleiben.",
    "Das Problem will ich nicht, zeig mir das N""\xe4""chste!",
    "Fr""\xfc""her war wirklich alles leichter. Zum Beispiel Ich.",
    "Als Gott mich schuf, grinste er und dachte: Keine Ahnung was passiert, aber lustig wirds bestimmt!",
    "Fahre nie schneller, als dein Schutzengel fliegen kann!",
    "Wer Ordnung h""\xe4""lt, ist nur zu faul zum Suchen.",
    "Gebildet ist, wer wei""\xdf"", wo er findet, was er nicht wei""\xdf"".",
    "I don't know where I'm going but I'm on my way.",
    "Humor ist versteckte Weisheit.",
    "Schokolade ist Gottes Entschuldigung f""\xfc""r Brokkoli.",
    "Wer schwankt hat mehr vom Weg!",
    "Da lernt man Dreisatz und Wahrscheinlichkeitsrechnung und steht trotzdem gr""\xfc""belnd vor dem Backofen, welche der vier Schienen nun die Mittlere ist.",
    "Ich schlafe im Sommer mit offenem Fenster. 1832 M""\xfc""cken gef""\xe4""llt das.",
    "Was ist ein Keks unter einem Baum? Ein schattiges Pl""\xe4""tzchen",
    "Nat""\xfc""rlich spreche ich mit mir selbst. Manchmal brauche ich eine kompetente Beratung.",
    "Wie, zu Fu""\xdf"" gehen? Hab doch vier gesunde Reifen!",
	// Murphys law
	"If anything can go wrong, it will.",
	"If anything just cannot go wrong, it will anyway.",
	"If everything seems to be going well, you have obviously overlooked something",
	"Smile . . . tomorrow will be worse.",
	"Matter will be damaged in direct proportion to its value.",
	"Research supports a specific theory depending on the amount of funds dedicated to it.",
	"In nature, nothing is ever right. Therefore, if everything is going right ... something is wrong.",
	"It is impossible to make anything foolproof because fools are so ingenious.",
	"Everything takes longer than you think.",
	"Every solution breeds new problems.",
	"The legibility of a copy is inversely proportional to its importance.",
	"A falling object will always land where it can do the most damage.",
	"A shatterproof object will always fall on the only surface hard enough to crack or break it.",
	"The other line always moves faster.",
	"In order to get a personal loan, you must first prove you don't need it.",
	"Anything you try to fix will take longer and cost you more than you thought.",
	"Build a system that even a fool can use, and only a fool will use it.",
	"Everyone has a scheme for getting rich that will not work.",
	"In any hierarchy, each individual rises to his own level of incompetence, and then remains there.",
	"There's never time to do it right, but there's always time to do it over.",
	"When in doubt, mumble. When in trouble, delegate.",
	"Anything good in life is either illegal, immoral or fattening.",
	"Murphy's golden rule: whoever has the gold makes the rules.",
	"A Smith & Wesson beats four aces.",
	"In case of doubt, make it sound convincing.",
	"Never argue with a fool, people might not know the difference.",
	"Whatever hits the fan will not be evenly distributed.",
	"Where patience fails, force prevails.",
	"Just when you think things cannot get any worse, they will.",
	"Great ideas are never remembered and dumb statements are never forgotten.",
	"When you see light at the end of the tunnel, the tunnel will cave in.",
	"Traffic is inversely proportional to how late you are, or are going to be.",
	"The probability of being observed is in direct proportion to the stupidity of ones actions.",
	"Those who know the least will always know it the loudest.",
	"Just because you CAN do something doesn't mean you SHOULD.",
	"Chaos always wins, because it's better organized.",
	"If at first you don't succeed destroy all evidence that you ever tried.",
	"It takes forever to learn the rules and once you've learned them they change again",
	"You will find an easy way to do it, after you've finished doing it.",
	"Anyone who isn't paranoid simply isn't paying attention.",
	"A valuable falling in a hard to reach place will be exactly at the distance of the tip of your fingers.",
	"The probability of rain is inversely proportional to the size of the umbrella you carry around with you all day.",
	"Nothing is impossible for the man who doesn't have to do it himself.",
	"The likelihood of something happening is in inverse proportion to the desirability of it happening.",
	"Common Sense Is Not So Common.",
	"Power Is Taken... Not Given.",
	"Two wrongs don't make a right. It usually takes three or four.",
	"The difference between Stupidity and Genius is that Genius has its limits.",
	"Those who don't take decisions never make mistakes.",
	"Anything that seems right, is putting you into a false sense of security.",
	"Its never so bad it couldn't be worse.",
	"When saying that things can not possibly get any worse - they will.",
	"The person ahead of you in the queue, will have the most complex transaction possible.",
	"Logic is a systematic method of coming to the wrong conclusion with confidence.",
	"Technology is dominated by those who manage what they do not understand.",
	"The opulence of the front office decor varies inversely with the fundamental solvency of the firm.",
	"The attention span of a computer is only as long as it electrical cord.",
	"Nothing ever gets built on schedule or within budget.",
	"The first myth of management is that it exists.",
	"A failure will not appear till a unit has passed final inspection.",
	"To err is human, but to really foul things up requires a computer.",
	"Any sufficiently advanced technology is indistinguishable from magic.",
	"Nothing motivates a man more than to see his boss putting in an honest day's work.",
	"Some people manage by the book, even though they don't know who wrote the book or even what book.",
	"To spot the expert, pick the one who predicts the job will take the longest and cost the most.",
	"After all is said and done, a hell of a lot more is said than done.",
	"The only perfect science is hind-sight.",
	"If an experiment works, something has gone wrong.",
	"When all else fails, read the instructions.",
	"The degree of technical competence is inversely proportional to the level of management.",
	"The remaining work to finish in order to reach your goal increases as the deadline approaches.",
	"It is never wise to let a piece of electronic equipment know that you are in a hurry.",
	"If you are not thoroughly confused, you have not been thoroughly informed.",
	"Standard parts are not.",
	"The bolt that is in the most awkward place will always be the one with the tightest thread.",
	"In today's fast-moving tech environment, it is a requirement that we forget more than we learn.",
	"It is simple to make something complex, and complex to make it simple.",
	"If it works in theory, it won't work in practice. If it works in practice it won't work in theory.",
	"Any tool dropped will fall where it can cause the most damage.",
	"When you finally update to a new technology, is when everyone stop supporting it.",
	"If you think you understand science (or computers or women), you're clearly not an expert",
	"Technicians are the only ones that don't trust technology.",
	"The repairman will have never seen a model quite like yours before.",
	"In theory there is no difference between theory and practice, but in practice there is.",
	"Never underestimate incompetency.",
	"Any given program, when running, is obsolete.",
	"Any given program costs more and takes longer each time it is run.",
	"If a program is useful, it will have to be changed.",
	"If a program is useless, it will have to be documented.",
	"Any given program will expand to fill all the available memory.",
	"Program complexity grows until it exceeds the capability of the programmer who must maintain it.",
	"Adding manpower to a late software project makes it later.",
	"No matter how many resources you have, it is never enough.",
	"If a program has not crashed yet, it is waiting for a critical moment before it crashes.",
	"Software bugs are impossible to detect by anybody except the end user.",
	"A failure in a device will never appear until it has passed final inspection.",
	"An expert is someone brought in at the last minute to share the blame.",
	"A patch is a piece of software which replaces old bugs with new bugs.",
	"The chances of a program doing what it's supposed to do is inversely proportional to the number of lines of code used.",
	"The longer it takes to download a program the more likely it won't run.",
	"It's not a bug, it's an undocumented feature.",
	"Bugs mysteriously appear when you say, Watch this!",
	"The probability of bugs appearing is directly proportional to the number and importance of people watching.",
	"If a project is completed on schedule, it wasn't debugged properly.",
	"If it works, it's production. If it doesn't, it's a test.",
	"Real programmers don't comment their code. If it was hard to write, it should be hard to understand.",
	"A computer that has been on the market for 6 weeks is still usable as a boat anchor.",
	"Computers let you waste time efficiently.",
	"A pat on the back is only a few inches from a kick in the pants.",
	"Don't be irreplaceable, if you can't be replaced, you can't be promoted.",
	"It doesn't matter what you do, it only matters what you say you've done and what you say you're going to do.",
	"The more crap you put up with, the more crap you are going to get.",
	"When the bosses talk about improving productivity, they are never talking about themselves.",
	"Mother said there would be days like this, but she never said there would be so many.",
	"--> The last person that quit or was fired will be the one held responsible for everything that goes wrong. :-)",
	"If it wasn't for the last minute, nothing would get done.",
	"The longer the title, the less important the job.",
	"If you have a little extra money to blow, something will break, and cost more than that little extra.",
	"If the salesperson says, All you have to do is..., you know you're in trouble.",
	// general
	"When I was a kid my parents moved a lot, but I always found them.",
	"Life is short. Smile while you still have teeth.",
	"The best way to teach your kids about taxes is by eating 30 percent of their ice cream.",
	"I’m writing a book. I’ve got the page numbers done.",
	"I have always wanted to be somebody, but I see now I should have been more specific.",
	"Knowledge is like underwear. It is useful to have it, but not necessary to show it off.",
	"If a book about failures doesn’t sell, is it a success?",
	"A lie gets halfway around the world before the truth has a chance to get its pants on.",
	"It’s okay if you don’t like me. Not everyone has good taste.",
	"Everything is changing. People are taking the comedians seriously and the politicians as a joke.",
	"I like long walks, especially when they are taken by people who annoy me.",
	"The only way to keep your health is to eat what you don’t want, drink what you don’t like, and do what you’d rather not.",
	"When nothing is going right, go left.",
	"Never miss a good chance to shut up.",
	"I’d like to live like a poor man – only with lots of money.",
	"My life feels like a test I didn’t study for.",
	"I don’t go crazy. I am crazy. I just go normal from time to time.",
	"My bed is a magical place where I suddenly remember everything I forgot to do.",
	"I’m actually not funny. I’m just really mean and people think I’m joking.",
	"Sometimes I want to go back in time and punch myself in the face.",
	"If you are lonely, dim all lights and put on a horror movie. After a while it won’t feel like you are alone anymore.",
	"Fries or salad? sums up every adult decision you have to make.",
	"If we’re not meant to have midnight snacks, why is there a light in the fridge.",
	"My doctor told me to watch my drinking. Now I drink in front of a mirror.",
	"I drive way too fast to worry about cholesterol.",
	"As your best friend I’ll always pick you up when you fall, after I finish laughing.",
	"Some people are like clouds. When they disappear, it’s a beautiful day.",
	"I’m not arguing. I’m simply explaining why I’m right.",
	"No wonder the teacher knows so much; she has the book.",
	"The most ineffective workers are systematically moved to the place where they can do the least damage: management.",
	"The best way to appreciate your job is to imagine yourself without one.",
	"If I had asked people what they wanted, they would have said faster horses. Henry Ford",
	"The closest a person ever comes to perfection is when he fills out a job application form.",
	"Don’t yell at your kids! Lean in real close and whisper, it’s much scarier.",
	"The quickest way for a parent to get a child’s attention is to sit down and look comfortable.",
	"I don’t know what’s more exhausting about parenting: the getting up early, or the acting like you know what you’re doing.",
	"It just occurred to me that the majority of my diet is made up of the foods that my kid didn’t finish.",
	"When your children are teenagers, it’s important to have a dog so that someone in the house is happy to see you.",
	"I never know what to say when people ask me what my hobbies are. I mean, I’m a dad.",
	"My wife and I were happy for twenty years. Then we met.",
	"Marriage…it’s not a word, it’s a sentence.",
	"Marry a man your own age; as your beauty fades, so will his eyesight.",
	"Marriage is the triumph of imagination over intelligence. Second marriage is the triumph of hope over experience.",
	"The most terrifying thing any woman can say to me is Notice anything different?",
	"When a man brings his wife flowers for no reason, there’s a reason."
};