#if defined(ESP8266) || defined(ESP32)
#include <pgmspace.h>
#else
#include <avr/pgmspace.h>
#endif

// I did not find a way to get the length of the array
#define WISDOM_NUMBER_OF_TEXTS          (47)

// Latin-1 character codes
// ä: "\xe4"
// ü: "\xfc"
// ö: "\xf6"
// Ä: "\xc4"
// Ö: "\xd6"
// Ü: "\xdc"
// ß: "\xdf"

const String wisdomTexts [] PROGMEM = {
    // Bullshit Bingo
    "Bingo 1: It works on my Machine!",
    "Bingo 2: It worked yesterday!",
    "Bingo 3: I've never done that before.",
    "Bingo 4: That's weird.",
    "Bingo 5: Where were you when the program blew up?",
    "Bingo 6: Why do you want to do it that way?",
    "Bingo 7: You can't use that version on your System!",
    "Bingo 8: Even though it doesn't work how does it feel?",
    "Bingo 9: Did you check for a Virus on your System?",
    "Bingo 10: Somebody must have changed my code!",
    "Bingo 11: It works, but it hasn't been tested.",
    "Bingo 12: THIS can't be the source of that!",
    "Bingo 13: I can't test everything.",
    "Bingo 14: It's just some unlucky coincidence.",
    "Bingo 15: You must have the wrong version!",
    "Bingo 16: I haven't touched that module in weeks.",
    "Bingo 17: There is something funky in your data.",
    "Bingo 18: What did you Type in to get it to crash?",
    "Bingo 19: It must be a hardware problem.",
    "Bingo 20: How is that possible?",
    "Bingo 21: That's scheduled to be fixed in the next release.",
    "Bingo 22: Yes, we knew that would happen.",
    "Bingo 23: Maybe we just don't support that platform.",
    "Bingo 24: It's a Feature we just haven't updated the specs.",
    "Bingo 25: Surely Nobody is going to use the program like that.",
    // Julia
    "So m""\xfc""de wie heute, war ich bestimmt seit gestern nicht mehr.",
    "Geschenke einpacken. Das r""\xfc""ckw""\xe4""rts einparken der Frauen f""\xfc""r M""\xe4""nner.",
    "Je gr""\xf6""ßer der Dachschaden desto besser der Blick auf die Sterne.",
    "Ich kann doch nicht alle gl""\xfc""cklich machen oder sehe ich aus wie ein Glas Nutella?!",
    "Lass uns lachen, das Leben ist ernst genug.",
    "Ich f""\xfc""hle mich, als k""\xf6""nnte ich B""\xe4""ume ausreissen. Also, kleine B""\xe4""ume. Vielleicht Bambus. Oder Blumen. Na gut. Gras. Gras geht.",
    "Nat""\xfc""rlich mache ich gerne Sport. Deshalb auch so selten. Soll ja schließlich was Besonderes bleiben.",
    "Das Problem will ich nicht, zeig mir das N""\xe4""chste!",
    "Fr""\xfc""her war wirklich alles leichter. Zum Beispiel Ich.",
    "Als Gott mich schuf, grinste er und dachte: Keine Ahnung was passiert, aber lustig wirds bestimmt!",
    "Fahre nie schneller, als dein Schutzengel fliegen kann!",
    "Wer Ordnung h""\xe4""lt, ist nur zu faul zum Suchen.",
    "Gebildet ist, wer wei""\xdf"", wo er findet, was er nicht wei""\xdf"".",
    "I don't know where I'm going but I'm on my way.",
    "Humor ist versteckte Weisheit.",
    "Schokolade ist Gottes Entschuldigung f""\xfc""r Brokkoli.",
    "Wer schwankt hat mehr vom Weg!",
    "Da lernt man Dreisatz und Wahrscheinlichkeitsrechnung und steht trotzdem gr""\xfc""belnd vor dem Backofen, welche der vier Schienen nun die Mittlere ist.",
    "Ich schlafe im Sommer mit offenem Fenster. 1832 M""\xfc""cken gef""\xe4""llt das.",
    "Was ist ein Keks unter einem Baum? Ein schattiges Pl""\xe4""tzchen",
    "Nat""\xfc""rlich spreche ich mit mir selbst. Manchmal brauche ich eine kompetente Beratung.",
    "Wie, zu Fu""\xdf"" gehen? Hab doch vier gesunde Reifen!",
    // Postillon Newsticker
    "+++ Z""\xe4""hlte bereits 60 Jahre: Amazon-Lagerist bei Inventur verstorben +++",
    "+++ Mag er roh nie: Mann kocht Nudelgericht +++",
    "+++ In G""\xe4""nsef""\xfc""""\xdf""chen gesetzt: Praktikant macht es sich bei 'Arbeit' im Schlachthof bequem +++",
    "+++ ""\xe4""tsch, Iran: Versteckte Kamera schickt englischen S""\xe4""nger in den nahen Osten +++",
    "+++ Multibl""\xe4""h-Pers""\xf6""nlichkeit: Psychisch Kranker kann als mehrere Menschen furzen +++",
    "+++ Nur ein paar Brocken: Englisch-Kenntnisse nicht ausreichend um Arzt den Grad der ""\xfc""belkeit zu erkl""\xe4""ren +++",
    "+++ Jahrelang Kohlgirl gewesen: Merkel spricht nicht gerne ""\xfc""ber ihre Anfangszeit +++",
    "+++ Kann ich mal Ihren Stift haben?: Azubi-Leihvertrag steht kurz vor der Unterzeichnung +++",
    "+++ Ersatzteil aus dem Second-Hand-Laden: Einarmiger Bandit repariert +++",
    "+++ ""\xfc""ber Welt tickendes Angebot: Swatch plant kostenlose Riesen-Uhr auf dem Mond +++",
    "+++ Wieder zu Hause aufgetaucht: H""\xe4""ftling gl""\xfc""ckt Flucht durch Kanalisation +++",
    "+++ Das Bett h""\xe4""utet ihm sehr viel: Mann h""\xe4""lt trotz unruhiger N""\xe4""chte an Schlafst""\xe4""tte aus Schlangenleder fest +++",
    "+++ Weltrekordhalter im Kraulen: Schwimmer verw""\xf6""hnt Katze +++",
    "+++ Opa-Hammer-Gau: Rentner f""\xe4""llt bei Passionsspielen Werkzeug auf Fu""\xdf"" +++",
    "+++ Essenzzeit: Mann nimmt Gericht aus Konzentraten ein +++",
    "+++ D""\xf6""ner Hebab: Turkish Airlines bietet an Bord nun auch Grillspezialit""\xe4""t an +++",
    "+++ Na, Geld: Alternder Callboy wird gefragt, warum er ""\xfc""berhaupt noch arbeitet +++",
    "+++ 20 Pfund abgenommen: Dicke Britin hetzt Taschendieb durch die ganze Stadt +++",
    "+++ Autorennlesung: Schriftsteller rezitiert sein Werk ""\xfc""ber Formel 1 Saison am N""\xfc""rburgring +++",
    "+++ 2G und SD: Veraltetes Handy h""\xe4""ngt in Baum +++",
    "+++ Beim Bund: General weist Soldaten auf Riss in Hose hin +++",
    "+++ Pfiff dezent: US Rapper bewies als Schiedsrichter kein Durchsetzungsverm""\xf6""gen +++", 
    "+++ Tubenarrest: Freche Zahnpasta muss drinnen bleiben +++",
    "+++ Schlimmen R""\xfc""ckfall erlitten: Alkoholiker konnte nicht wieder stehen +++",
    "+++ War nicht ohne: Mann von Safer Sex begeistert +++",
    "+++ Will da auch gar nichts besch""\xf6""nigen: Plastischer Chirurg nimmt Patientin jede Hoffnung +++",
    "+++ Zwei Dijons: Senfhersteller bringt Ex-Freundin Geschenk +++", 
    "+++ Helles Lager: Getr""\xe4""nkemarktmitarbeiter findet Bier schneller +++",
    "+++ Erwischt: Frau beobachtet ihren Mann beim Tindern +++",
    "+++ Aus dem Bauch heraus: Von Wal verspeister Mann verfasst spontan seine Memoiren +++",
    "+++ Herdzinsangelegenheit: Kunde m""\xf6""chte Ofen liebend gern auf Raten zahlen +++",
    "+++ Rotes Kreuz: Rettungssanit""\xe4""ter klagt ""\xfc""ber R""\xfc""ckenschmerzen nach S/M-Wochenende +++",
    "+++ Tarte ""\xfc"", Tarte A: B""\xe4""cker wegen verr""\xfc""ckter Nummerierung in Psychiatrie eingeliefert +++",
    "+++ Muss neuen aufsetzen: Mann sch""\xfc""ttet sich Kaffee ""\xfc""ber den Hut +++",
    "+++ Springer Steve L.: Neonazi trug beim Suizid seine Lieblingsschuhe +++",
    "+++ Hintergrund unklar: Maler zerst""\xf6""rt Stillleben +++",
    "+++ Im Karsten: Schwulenporno endlich fertig +++",
    "+++ Nur eine Kugel: Revolverheld erschie""\xdf""t knausrigen Eisdielenkunden +++",
    "+++ War noch gr""\xfc""n hinter Tenoren: Fahranf""\xe4""nger rast auf Kreuzung in Tourbus-Heck +++",
    "+++ Speichermedium: Auf Dachboden lebende Frau mit ""\xfc""bernat""\xfc""rlichen F""\xe4""higkeiten findet USB-Stick +++",
    "+++ Thomas' Scotch-Alk: Whisky von Showmaster entwendet +++",
    "+++ Alles au""\xdf""er Kontrolle: T""\xfc""rsteher nahm Job nicht ernst +++",
    "+++ Mittags Sch""\xe4""fchen gehalten: Hirte macht Pause mit Lamm im Arm +++",
    "+++ Tausend Zsa Zsa: Trickreicher Erfinder klont mehrfach Hollywoodlegende +++",
    "+++ Sitzt gut: H""\xe4""ftling mit Kleidung und Schemel zufrieden +++",
    "+++ S""\xe4""uchenschutzgesetz: Kleine Schweine m""\xfc""ssen bei Pandemie als erstes gerettet werden +++",
    "+++ Beh""\xe4""lter f""\xfc""r sich: Betrunkener erkl""\xe4""rt auf Party nicht, warum er Eimer dabei hat +++",
    "+++ Rasch aua: Autobahn""\xfc""berquerung zu Fuß endet im Krankenhaus +++",
    "+++ Da kennt er nix: Vollidiot meldet sich zu Astrophysik-Quiz an +++",
    "+++ Social Diss-Dancing: Waldorfsch""\xfc""ler postet beleidigende Videos auf Facebook +++",
    "+++ Der totale Kn""\xfc""ller: Kopierer bricht Verkaufsrekorde trotz schlechten Papiereinzugs +++",
    "+++ Qual-Lied-Hetz-Management: Nach ISO9001 ist es erlaubt, ""\xfc""ber 'Atemlos durch die Nacht' herzuziehen +++",
    "+++ Steckt in Apache: Winnetou in flagranti mit Liebhaber erwischt +++",
    "+++ Streit ""\xfc""ber fehlende Stra""\xdf""e eskaliert: B""\xfc""rgermeister schickt Erschlie""\xdf""ungskommando +++",
    "+++ Schwamm: SpongeBob besteht Seepferdchen +++",
    "+++ F""\xfc""hrt ein Schattendasein: Von Hand auf Leinwand projiziertes Krokodil +++",
    "+++ Ernie Dirigent: Bert erlebt Berufung von Freund zum Orchesterleiter als Dem""\xfc""tigung +++",
    "+++ Wegen Kontaktsperre: Batterie verweigert Dienst +++",
    "+++ Nach dem Stunt teert Inge: Filmdouble muss voraussichtlich Zweitjob im Stra""\xdf""enbau annehmen +++",
    "+++ Geh""\xf6""ren zur Riesigkotgruppe: Dicke leiden unter Klopapiermangel +++",
    "+++ Bekam einen R""\xfc""ffel: Zahnloser muss sich zur Strafe als Elefant verkleiden +++",
    "+++ Hahn-Twerker: Zimmermann macht Potanz-Video im Gockel-Kost""\xfc""m +++",
    "+++ Unterschiedliche Vorstellungen: Kinobesitzerehepaar trennt sich +++",
    "+++ Siel bereisen: Florian macht Deichtour +++",
    "+++ Macht sich nichts vor: Pfleger wei""\xdf"" eigentlich, dass Ansteckungsrisiko ohne Mundschutz gr""\xf6""""\xdf""er ist +++",
    "+++ K. Russell: Schauspieler nutzt Fahrgesch""\xe4""ft +++",
    "+++ Zieht Schlussstrich: Mann trennt sich von Lieblingsstift +++",
    "+++ Prinzessbohnen: K""\xf6""nig r""\xe4""t seinem Sohn zu mehr Gem""\xfc""se +++",
    "+++ K""\xf6""nnte jeden treffen: Mann immun gegen Coronavirus +++",
    "+++ In Skiflagge geraten: Insolventer Quizteilnehmer tr""\xe4""gt Riesenslalomzubeh""\xf6""r als Schal +++",
    "+++ Wegen Best""\xe4""ubungsmitteln: Biene verhaftet +++",
    "+++ Eilegeboten: Kundschafter mahnen H""\xfc""hner zu rechtzeitiger Steigerung der Produktion bis Ostern +++",
    "+++ Verein-Zelt: Sch""\xfc""tzenfest-Pavillon darf nur noch von je einem Mitglied betreten werden +++",
    "+++ Stoff vers""\xe4""umt: N""\xe4""herin muss nach Feierabend noch f""\xfc""r Kurs lernen +++",
    "+++ Stand dort: Wanderer sah auf Umgebungsplan, wo er sich befand +++",
    "+++ In Betrieb genommen: Sexroboter vor Auslieferung getestet +++",
    "+++ Wertpapiere: Banker investiert in Toilettenrollen +++",
    "+++ Musste dem Rechnung tragen: Frau akzeptiert, dass Freund nach Leistenbruch unm""\xf6""glich Kassenzettel heben kann +++",
    "+++ Hat endlich eine Rolle ergattert: Erfolgloser Schauspieler bringt Klopapier nach Hause +++",
    "+++ Stand kurz vor einer L""\xf6""sung: Impfstoffentwickler atmet hochgiftige D""\xe4""mpfe ein +++",
    "+++ S. Raab bellt im Karton: Entertainer hat den Verstand verloren +++",
    "+++ F""\xe4""llt leicht: Neymar auch in Verkleidung unschwer zu erkennen +++",
    "+++ Total vervirt: Coronapatient l""\xe4""uft orientierungslos durch Fu""\xdf""g""\xe4""ngerzone +++",
    "+++ 'Wang, w""\xfc""rz mal Widder...richtig so...mehr!': Carrell empfand Hammelfleisch am China-Imbiss als zu fad +++",
    "+++ Brachte nur noch Vieren nach Hause: Familie von schlechtem Sch""\xfc""ler in Quarant""\xe4""ne +++",
    "+++ Dia mit Lungen aufgenommen: Polizei jagt Organfotografen +++",
    "+++ Einrichtungshaus: IKEA mahnt Kunden zur Einhaltung der Laufroute +++",
    "+++ Trampolin: Warschauerin nimmt H""\xfc""pfger""\xe4""t mit in die Stra""\xdf""enbahn +++",
    "+++ Mustafa werden: Muslima will nach Geschlechtsumwandlung dominanter auftreten +++",
    "+++ Das wird sich noch zeigen: Murmeltierexperte streitet mit entt""\xe4""uschten Touristen ""\xfc""ber seine Fachkompetenz +++",
    "+++ 'Husten! Wir haben ein Problem.': ISS meldet ersten Corona-Fall +++",
    "+++ Macht jetzt in Antiquit""\xe4""ten: Vasenh""\xe4""ndler findet kein Klo +++",
    "+++ F""\xfc""hrt Ananas-Serum: Arzt t""\xe4""uscht Patienten mit Impfstoff aus Fruchtsaft +++",
    "+++ Immer nur Fish &amp;amp; Ships: Godzilla findet englische K""\xfc""che ""\xf6""de +++",
    "+++ h.c. nicht alle: Uni-Rektor stellt fast nur Dozenten mit Ehrendoktorw""\xfc""rde ein +++",
    "+++ Waren verdorben: Ordin""\xe4""re Marktfrauen boten faules Obst an +++",
    "+++ Eine einzige Schikane: Formel-1-Fahrer ""\xfc""ber schlechten Kurs emp""\xf6""rt +++",
    "+++ File geboten: Datei zu verkaufen +++",
    "+++ Schnappt nach Luft: Hund dreht in Sauna durch +++",
    "+++ 'Kiek, Erik, ih!': Berlinerin zeigt ihrem Freund toten Hahn +++",
    "+++ Nicht auszumalen: Kinderbuch mit 10.000 Seiten ver""\xf6""ffentlicht +++",
    "+++ Schlafend gestellt: Einbrecher lag bei Zugriff noch im Bett +++",
    "+++ finnish.net: Homepage in Helsinki f""\xfc""r Hessen unm""\xf6""glich zu erreichen +++",
    "+++ Arbeitet fieberhaft: Immunsystem l""\xe4""uft auf Hochtouren +++",
    "+++ Petryschale: Frauke z""\xfc""chtet Halsw""\xe4""rmer im Labor +++",
    "+++ Hinter Heer ist man schlauer: Soldat will nicht an die Front +++",
    "+++ Fellig losgel""\xf6""st: Major Tom startete unrasiert +++",
    "+++ 'Sch""\xfc""tt Senf herein!': Jugendlicher stiftet Kumpel an, Schie""\xdf""sport-Club einen Streich zu spielen +++",
    "+++ Leckt ein bisschen: Chemiker untersucht unbekannte Substanz unter Silo +++",
    "+++ Dieb rennt: Fl""\xfc""chtiger Taschenr""\xe4""uber z""\xfc""ndete Opfer an +++",
    "+++ Muss zum K""\xe4""ferorthop""\xe4""den: Insekt hat ""\xfc""berbiss +++",
    "+++ Punk kaut Tomaten: Linker Veganer hebt mehrfach Geld ab +++",
    "+++ Spricht mit gespaltener Zunge: Indianer  l""\xfc""gt ""\xfc""ber Unfall mit Jagdmesser +++",
    "+++ Wiesloch: Frau aus Baden-W""\xfc""rttemberg s""\xe4""uft +++",
    "+++ Patienten m""\xfc""ssen mit gr""\xf6""""\xdf""eren Einschnitten rechnen: Chirurgiepraxis spart an feinen Skalpellen +++",
    "+++ Ein sch""\xf6""ner Zug von ihm: Modell-Eisenbahner verschenkt sein liebstes Exemplar +++",
    "+++ Da gibts Gedr""\xe4""nge: Hohes Menschenaufkommen bei hessischem Spirituosenh""\xe4""ndler +++",
    "+++ Arsch reckend: Immer mehr M""\xe4""nner gehen in Yoga-Kurs +++",
    "+++ PDF: Geheimes Dokument offenbart verkehrte Politik der FDP +++",
    "+++ H""\xe4""ufig in Elefantenporno zu sehen: Sto""\xdf""szene +++",
    "+++ Ging ihm dann auch direkt auf: Mann h""\xe4""tte Hosenrei""\xdf""verschluss vor Vorstellungsgespr""\xe4""ch besser repariert +++",
    "+++ Ein einmaliges Erlebnis:  Marodes Bungeeunternehmen versucht es mit ehrlicher Werbung +++", 
    "+++ Gold richtig: Quizshow-Teilnehmer beantwortet Frage nach Edelmetall +++", 
    "+++ Ein Fach nur, d""\xe4""mlich: Merkw""\xfc""rdiger Apothekerschrank floppt +++", 
    "+++ Die wichtigsten Wokgabeln: Asiatischer Koch paukt f""\xfc""r Pr""\xfc""fung in Besteckkunde +++", 
    "+++ Rote Arme Fraktion: Andreas Baader und Ulrike Meinhof haben Sonnenbrand +++", 
    "+++ Hat ihn dumm angemacht: Vegetarier von Salat verpr""\xfc""gelt +++", 
    "+++ Er ist jetzt an einem besseren Ort: Journalist springt aus dem Fenster der BILD-Redaktion +++",
    "+++ War als erster an der Ziehlinie: Junkie gewinnt Wettrennen um Kokain +++",
    "+++ Aphte: Nazi wegen Mundh""\xf6""hlenentz""\xfc""ndung unf""\xe4""hig, seine Lieblingspartei zu nennen +++",
    "+++ Kann ein Liter Fond singen: Mann wei""\xdf"", wie es ist, beim Tr""\xe4""llern Bratensaft zu produzieren +++",
    "+++ War eiskalt vor dem Tor: Platzwart findet erfrorenen St""\xfc""rmer +++",
    "+++ Will nicht, dass jeder seinen Schwan zieht: Bekleideter Mann bindet Wasservogel an +++",
    "+++ Ein Schlag ins Gesicht: Masochist von entt""\xe4""uschendem Domina-Angebot gekr""\xe4""nkt +++",
    "+++ Serge ade: Bayernspieler muss trotz hervorragender Leistungen den Verein verlassen +++",
    "+++ ""\xfc""ber Alf lecken: Masernpatient versucht Krankheit durch Lutschen an Au""\xdf""erirdischem zu lindern +++",
    "+++ Wie die Lehm-Inge: Kinder beim T""\xf6""pfern von Klippe gesprungen +++",
    "+++ '""\xe4""hm, Sie Hemmer!': Rapper als Spa""\xdf""bremse beschimpft +++",
    "+++ Wageneber im Kofferraum: Franzose mit Reifenpanne hatte Schwein +++",
    "+++ Steiffhundfest: Kind behauptet, sein Stofftier habe Geburtstag +++",
    "+++ War am saugen: Ehefrau ""\xfc""berrascht ihren Mann mit neuer Haushaltshilfe +++",
    "+++ Gingen um die Welt: Bilder von Extremdistanz-Wanderern in allen Nachrichten pr""\xe4""sent +++",
    "+++ Bekommt lecker Li: Kampfhund wird mit Chinesen belohnt +++",
    "+++ Ohne Witz: Mario Barth ist nicht lustig +++",
    "+++ Freut sich auf 'at home-Pils': Nuklearphysiker hat Feierabend +++",
    "+++ Zweibr""\xfc""cken: Zahn""\xe4""rztin aus der Pfalz erlebt ruhigen Vormittag +++",
    "+++ Irre summen: Anwohner m""\xfc""ssen f""\xfc""r L""\xe4""rmschutzwand vor Psychiatrie zahlen +++",
    "+++ H""\xf6""ren sich gegenseitig ab: Spionage-Azubis lernen f""\xfc""r ihre Abschlusspr""\xfc""fung +++",
    "+++ Kaviar im Zeugnis: Bayerischer Lehrer belohnt rogens""\xfc""chtigen Sch""\xfc""ler +++",
    "+++ Genfer: Zahnloser Schweizer gibt sich f""\xfc""r ehemaligen deutschen Au""\xdf""enminister aus +++",
    "+++ Lange nicht Font""\xe4""nen geh""\xf6""rt: Meeresanwohner wundert sich, wo Wale geblieben sind +++"
};